### Create a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "qwerty"
}

### Get user by id
GET http://localhost:3000/auth/2

### Get user by email
GET http://localhost:3000/auth?email=test1@gmail.com

### Delete a user
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "NOTTEST@gmail.com"
}
